name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development-reza
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Analyze, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build Release APK
        if: github.ref == 'refs/heads/main'
        run: flutter build apk --release

      - name: Upload APK Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk